apiVersion: v1
kind: Service
metadata:
  name: docker-service
spec:
  type: LoadBalancer   # Use NodePort if not on cloud
  selector:
    app: docker-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
